### ISSUE TITLE
Cannot have more than one multiselect on a page

### ISSUE THREAD

**Issue by TallGirlVanessa** [zraly/mistral-ui#3]
I'm not very familiar with AlpineJS, but it seems there's some issue where two multiselects on the same page share the same state. Is there a way to isolate each instance?

## Steps to reproduce

1. Create two multiselect selects on the same page, with different names, but the same list of options.
2. Pick some options from the first select.

## Expected result

The selected options are displayed in the first select.

## Actual result

The count on the first select increments, but no names of options are displayed. The options are instead displayed in the second select.

**Comment by TallGirlVanessa** [comment]
Thank you for this project btw, it's very pretty!

**Comment by zraly** [comment]
You are right, more multiselects don't work. I have to solve this.

> Thank you for this project btw, it's very pretty!

Thank you!

**Comment by zraly** [comment]
It should now be fixed in version 1.4.0
